src/Entity/Articles.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\ArticlesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
#[ApiResource]
#[ORM\Entity(repositoryClass: ArticlesRepository::class)]
class Articles
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\Column(length: 255)]
    private ?string $short_description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $insert_date = null;

    /**
     * @var Collection<int, Categories>
     */
    #[ORM\ManyToMany(targetEntity: Categories::class, inversedBy: 'articles')]
    private Collection $categories;

    /**
     * @var Collection<int, Comments>
     */
    #[ORM\OneToMany(targetEntity: Comments::class, mappedBy: 'article_id')]
    private Collection $comments;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getShortDescription(): ?string
    {
        return $this->short_description;
    }

    public function setShortDescription(string $short_description): static
    {
        $this->short_description = $short_description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getInsertDate(): ?\DateTimeInterface
    {
        return $this->insert_date;
    }

    public function setInsertDate(\DateTimeInterface $insert_date): static
    {
        $this->insert_date = $insert_date;

        return $this;
    }

    /**
     * @return Collection<int, Categories>
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Categories $category): static
    {
        if (!$this->categories->contains($category)) {
            $this->categories->add($category);
        }

        return $this;
    }

    public function removeCategory(Categories $category): static
    {
        $this->categories->removeElement($category);

        return $this;
    }

    /**
     * @return Collection<int, Comments>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setArticleId($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getArticleId() === $this) {
                $comment->setArticleId(null);
            }
        }

        return $this;
    }



}

src/Form/ArticlesType.php
<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticlesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('field_name')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            // Configure your form options here
        ]);
    }
}

src/Controller/ArticleController.php
<?php
namespace App\Controller;

use App\Entity\Articles;
use App\Entity\Categories;
use App\Form\ArticlesFromType;
use App\Repository\ArticlesRepository;
use App\Service\ArticleService;
use App\Service\CategoryService;
use App\Service\ImageUploaderService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class ArticleController extends AbstractController
{
    private $ArticleService;
    private $CategoryService;
    private $ImageUploaderService;

    public function __construct(
        ArticleService $ArticleService,
        CategoryService $CategoryService,
        ImageUploaderService $ImageUploaderService
    ) {
        $this->ArticleService = $ArticleService;
        $this->CategoryService = $CategoryService;
        $this->ImageUploaderService = $ImageUploaderService;
    }

    public function Index(ArticlesRepository $ArticlesRepository): Response
    {
        $Articles = $ArticlesRepository->findAll();

        return $this->render('admin/articles/index.html.twig', [
            'Articles' => $Articles
        ]);
    }

    public function ArticlesByCategory(
        Categories $Category,
        int $Page
    ): Response {
        $Category = $this->CategoryService->GetCategoryById($Category->getId());
        $CategoryTitle = $Category->getTitle();

        $Result = $this->ArticleService->GetArticlesByCategory($Category->getId(), $Page);

        return $this->render('main/articles/by_category.html.twig', [
            'CategoryTitle' => $CategoryTitle,
            'Paginator' => [
                'MaxPages' => $Result['MaxPages'],
                'CurrentPage' => $Result['CurrentPage'],
                'CategoryId' => $Category->getId(),
            ],
            'Articles' => $Result['Articles']
        ]);
    }

    public function Article(Articles $Article, ArticlesRepository $ArticlesRepository): Response
    {
        $Article = $ArticlesRepository->find($Article->getId());
        $Categories = $Article->getCategories()->toArray();

        return $this->render('main/articles/index.html.twig', [
            'Article' => $Article,
            'Categories' => $Categories
        ]);
    }

    public function Edit(
        Request $Request,
        Articles $Article,
        ArticlesRepository $ArticlesRepository
    ): Response {
        $Article = $ArticlesRepository->find($Article->getId());
        $Form = $this->createForm(ArticlesFromType::class, $Article);
        $Form->handleRequest($Request);

        if ($Form->isSubmitted() && $Form->isValid()) {
            if ($Image = $Request->files->get('articles_from')['image']) {
                $NewFileName = $this->ImageUploaderService->Upload($Image);
                $Article->setImage($NewFileName);
            }

            $this->ArticleService->SaveArticle($Article);
            $this->addFlash('Messages', 'Article edited successfully!');

            return $this->redirect($this->generateUrl('admin_articles'));
        }

        return $this->render('admin/articles/edit.html.twig', [
            'Form' => $Form->createView()
        ]);
    }

    public function Add(Request $Request): Response
    {
        $Article = new Articles();
        $Form = $this->createForm(ArticlesFromType::class, $Article);
        $Form->handleRequest($Request);

        if ($Form->isSubmitted() && $Form->isValid()) {
            if ($Image = $Request->files->get('articles_from')['image']) {
                $NewFileName = $this->ImageUploaderService->Upload($Image);
                $Article->setImage($NewFileName);
            }

            $this->ArticleService->SaveArticle($Article);
            $this->addFlash('Messages', 'Article added successfully!');

            return $this->redirect($this->generateUrl('admin_articles'));
        }

        return $this->render('admin/articles/add.html.twig', [
            'Form' => $Form->createView()
        ]);
    }

    public function Remove(Articles $Article): Response
    {
        $this->ArticleService->RemoveArticle($Article);
        $this->addFlash('Messages', 'Article removed successfully!');

        return $this->redirect($this->generateUrl('admin_articles'));
    }
}

templates/main/articles/elements/list.html.twig
{% for Article in Articles %}

    <div class="col-lg-4 mt-4">
        <div class="card" >

            {% if Article.image %}
                <img src="/uploads/{{ Article.image }}" class="card-img-top" alt="{{ Article.title }}">
            {% else %}
                <img src="/assets/images/no-image.jpg" class="card-img-top" alt="{{ Article.title }}">
            {% endif %}

            <div class="card-body">
                <h5 class="card-title mt-2 mb-3">
                    <a href="{{ path('article', {'id' : Article.id}) }}">{{ Article.title }}</a>
                </h5>
                <p class="card-text"> {{ Article.shortDescription }} </p>

                {% set Categories = Article.getCategories().toArray() %}
                <div class="d-block mt-2 mb-3">
                    {% include '/main/categories/elements/list.html.twig' %}
                </div>

                <a href="{{ path('article', {'id' : Article.id}) }}" class="btn btn-primary">See More</a>
            </div>

        </div>
    </div>

{% endfor %}

templates/main/articles/elements/paginator.html.twig
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">

        <li class="page-item {{ Paginator.currentPage == 1 or Paginator.currentPage == 0 ? 'disabled' }} ">

            {% if Paginator.currentPage is defined and Paginator.currentPage > 1 %}
                {% set precedent = Paginator.currentPage - 1 %}
            {% else %}
                {% set precedent = 1 %}
            {% endif %}

            <a class="page-link" href="
                {{
                    path(
                        'articles_by_category',
                        {
                            'Page' : precedent,
                            'Category' : Paginator.categoryId
                        }
                    )

                }}">
                <span aria-hidden="true">&laquo;</span>
            </a>

        </li>

        {% if Paginator.maxPages / 10 > 6 %}

            <li class="page-item">
                <a class="page-link" href="
                    {{
                        path(
                            'articles_by_category',
                            {
                                'Page' : 1,
                                'Category' : Paginator.categoryId
                            }
                        )
                    }}">1</a>
            </li>

            {% for item in 1..5 %}
                <li class="pazge-item">
                    <a class="page-link " href="{{
                        path(
                            'articles_by_category',{
                            'Page' : (Paginator.maxPages / 10 / 6 * loop.index) | number_format(0),
                            'Category' : Paginator.categoryId}
                        )
                    }}">
                        {{
                            (Paginator.maxPages / 10 / 6 * loop.index) | number_format(0)
                        }}
                    </a>
                </li>
            {% endfor %}

            <li class="page-item">
                <a class="page-link" href={{
                    path(
                        'articles_by_category',
                        {
                            'Page' : (paginator.maxPages / 10) | number_format(0),
                            'Category' : paginator.categoryId}
                    )
                }}>
                    {{
                        (paginator.maxPages / 10) | number_format(0)
                    }}</a>
            </li>

        {% else %}
            {% for item in 1..(Paginator.maxPages / 10) | number_format(0) %}

                <li class="page-item {% if Paginator.currentPage == loop.index %} active {% endif %}">
                    <a class="page-link " href="{{
                        path(
                            'articles_by_category',
                            {
                                'Page' : loop.index,
                                'Category' : Paginator.categoryId
                            }
                        ) }}">{{loop.index}}</a>
                </li>

            {% endfor %}
        {% endif %}


        <li class="page-item {{ Paginator.currentPage >= (Paginator.maxPages / 10) | number_format ? 'disabled' }}">

            {% if Paginator.currentPage == 0 %}
                {% set suivant = 2 %}
            {% else %}
                {% set suivant = Paginator.currentPage + 1 %}
            {% endif %}

            <a class="page-link" href="{{
                path('articles_by_category', {
                    'Page' : suivant,
                    'Category' : Paginator.categoryId
                    }
                )
            }}">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>

    </ul>
</nav>